---
# yaml-language-server: $schema=https://json.schemastore.org/pre-commit-config.json
# For more hooks, see https://pre-commit.com/hooks.html
repos:
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 3.6.0
    hooks:
      - id: editorconfig-checker
        alias: ec

  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.2
    hooks:
      - id: go-build-mod
        alias: build
      - id: go-mod-tidy
        alias: tidy
      - id: go-revive
        alias: revive
      - id: go-vet-mod
        alias: vet
      - id: go-staticcheck-mod
        alias: static
      - id: go-fmt
        alias: fmt
      - id: go-sec-mod
        alias: sec
